BEGIN;

-- Nettoyage des tables dans l'ordre inverse des dépendances
DROP TABLE IF EXISTS "order_item";
DROP TABLE IF EXISTS "product_location";
DROP TABLE IF EXISTS "log";
DROP TABLE IF EXISTS "order";
DROP TABLE IF EXISTS "product";
DROP TABLE IF EXISTS "location";
DROP TABLE IF EXISTS "user";


CREATE TABLE "user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "firstname" VARCHAR(255) NOT NULL,
    "lastname" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "status" VARCHAR(50) NOT NULL CHECK (status IN ('particulier','association','entreprise')),
    "role" VARCHAR(50) NOT NULL DEFAULT 'member' CHECK (role IN ('member','admin'))
);

CREATE TABLE product (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "price" DECIMAL(10,2) NOT NULL DEFAULT 0.0,
    "description" VARCHAR(10000) NOT NULL,
    "image_url" TEXT[] NOT NULL,
    "available" BOOLEAN NOT NULL DEFAULT false,
    "stock" INT NOT NULL DEFAULT 0,
     CHECK (array_length(image_url, 1) <= 10)
);

CREATE TABLE "order" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "date" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "status" VARCHAR(20) NOT NULL CHECK (status IN ('pending','paid','cancelled')),
    "total" DECIMAL(10,2) NOT NULL DEFAULT 0.0,
    "user_id" INT NOT NULL REFERENCES "user"(id) ON DELETE SET NULL
);

CREATE TABLE log (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "level" VARCHAR(20) NOT NULL CHECK (level IN ('info','warning','error')),
    "message" VARCHAR(10000) NOT NULL,
    "context" JSONB,
    "user_id" INT REFERENCES "user"(id) ON DELETE SET NULL
);

CREATE TABLE product_location (
    "product_id" INT NOT NULL REFERENCES "product"(id) ON DELETE CASCADE,
    "location_id" INT NOT NULL REFERENCES "location"(id) ON DELETE CASCADE,
    PRIMARY KEY ("product_id", "location_id")
);

CREATE TABLE order_item (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" INT NOT NULL REFERENCES "order"(id) ON DELETE CASCADE,
    "product_id" INT NOT NULL REFERENCES "product"(id),
    "quantity" INT NOT NULL DEFAULT 1,
    "unit_price" DECIMAL(10,2) NOT NULL
);

COMMIT;

// Se connecter à PSQL: sudo -i -u postgres psql
// Ou : psql -h localhost -U postgres
// MDP : titimdp

// Créer un utilisateur: CREATE USER trombiuser WITH ENCRYPTED PASSWORD 'trombipass';
// Créer une base de données: CREATE DATABASE greenroots OWNER postgres;

// Se connecter à une base de données dans psql: psql -U NOM -d NOMBASEDEDONNEES
// Supprimer une base de données: DROP DATABASE trombi;


// \l pour lister les bases de données
// \du pour lister les utilisateurs (ou « roles ») existants
// \dt pour lister les tables de la base de données courante
// \c nombdd pour se connecter à une base de données en particulier
// \d nomTable pour voir les détails des champs d'une table

// Gérer les droits PSQL: sudo nano /etc/postgresql/16/main/pg_hba.conf
// Relancer le serveur PostgreSQL: sudo service postgresql restart


// Script package.json:
// npm run db:create
// "db:create": "psql -U NOMUSER -d NomDB -f ./data/create-db.sql
// Se connecter à PSQL: sudo -i -u postgres psql
// Ou : psql -h localhost -U postgres
// MDP : titimdp
// Ou : psql -h localhost -U postgres
// MDP : titimdp