@startuml GreenRoots

left to right direction

actor Visiteur
actor Membre
actor Admin

Visiteur --|> Membre
Membre --|> Admin

rectangle "GreenRoots - Cas d'utilisation" {

  ' --- Admin ---
  usecase "Gérer produits (CRUD)" as UC22
  usecase "Gérer utilisateurs" as UC23
  usecase "Gérer commandes" as UC24

  ' --- Membre ---
  usecase "Procéder au paiement" as UC12
  usecase "Recevoir confirmation commande" as UC13
  usecase "Suivre commande" as UC14
  usecase "Voir historique commandes" as UC15
  usecase "Modifier mes infos perso" as UC17
  usecase "Supprimer mon compte" as UC18
  usecase "Me déconnecter" as UC19

  ' --- Visiteur ---
  usecase "Accéder à l'accueil" as UC1
  usecase "Créer un compte" as UC2
  usecase "Se connecter" as UC3
  usecase "Consulter à propos" as UC4
  usecase "Consulter contact" as UC5
  usecase "Consulter mentions légales" as UC6
  usecase "Voir catalogue produits" as UC7
  usecase "Rechercher/filtrer produits" as UC8
  usecase "Voir détail produit" as UC9
  usecase "Ajouter produit au panier" as UC10
  usecase "Voir panier" as UC11
}

' Liens Admin
Admin --> UC22
Admin --> UC23
Admin --> UC24

' Liens Membre
Membre --> UC12
Membre --> UC13
Membre --> UC14
Membre --> UC15
Membre --> UC17
Membre --> UC18
Membre --> UC19

' Liens Visiteur
Visiteur --> UC1
Visiteur --> UC2
Visiteur --> UC3
Visiteur --> UC4
Visiteur --> UC5
Visiteur --> UC6
Visiteur --> UC7
Visiteur --> UC8
Visiteur --> UC9
Visiteur --> UC10
Visiteur --> UC11

@enduml
