-- Active: 1753280674213@@127.0.0.1@5432@greenroots
BEGIN;

-- Nettoyage des tables dans l'ordre inverse des dépendances
DROP TABLE IF EXISTS "refresh_token";
DROP TABLE IF EXISTS "order_item";
DROP TABLE IF EXISTS "product_location";
DROP TABLE IF EXISTS "log";
DROP TABLE IF EXISTS "order";
DROP TABLE IF EXISTS "product";
DROP TABLE IF EXISTS "location";
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "user_type";

-- =======================================
-- TABLE user_type
-- =======================================
CREATE TABLE "user_type" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "code" VARCHAR(50) UNIQUE NOT NULL,
    "label" VARCHAR(255) NOT NULL,
    "tva_rate" DECIMAL(5,2) NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =======================================
-- TABLE user
-- =======================================
CREATE TABLE "user" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "firstname" VARCHAR(255) NOT NULL,
    "lastname" VARCHAR(255) NOT NULL,
    "email" VARCHAR(320) UNIQUE NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "role" VARCHAR(50) NOT NULL DEFAULT 'member' CHECK (role IN ('member','admin')),
    "user_type_id" INT NOT NULL REFERENCES "user_type"(id) ON DELETE RESTRICT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "deleted_at" TIMESTAMPTZ DEFAULT NULL
);

-- =======================================
-- TABLE refresh_token
-- =======================================

CREATE TABLE "refresh_token" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "token" TEXT NOT NULL,
    "user_id" INT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "expired_at" TIMESTAMPTZ NOT NULL
);

-- =======================================
-- TABLE product
-- =======================================
CREATE TABLE "product" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "slug" VARCHAR(255) UNIQUE NOT NULL,
    "price" DECIMAL(10,2) NOT NULL DEFAULT 0.0,
    "description" VARCHAR(2500) NOT NULL,
    "image_urls" TEXT[] NOT NULL,
    "available" BOOLEAN NOT NULL DEFAULT true,
    "stock" INT NOT NULL DEFAULT 0,
    "scientific_name" VARCHAR(255),
    "carbon" DECIMAL(10,2),
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (array_length(image_urls, 1) <= 10)
);

-- =======================================
-- TABLE location
-- =======================================
CREATE TABLE "location" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "latitude" DOUBLE PRECISION NOT NULL,
    "longitude" DOUBLE PRECISION NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =======================================
-- TABLE order
-- =======================================
CREATE TABLE "order" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "status" VARCHAR(20) NOT NULL CHECK (status IN ('pending','paid','cancelled')),
    "user_id" INT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT,
    "total" DECIMAL(10,2) NOT NULL DEFAULT 0.0,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =======================================
-- TABLE order_item
-- =======================================
CREATE TABLE "order_item" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" INT NOT NULL REFERENCES "order"(id) ON DELETE CASCADE,
    "product_id" INT NOT NULL REFERENCES "product"(id),
    "quantity" INT NOT NULL DEFAULT 1,
    "unit_price" DECIMAL(10,2) NOT NULL
);

-- =======================================
-- TABLE product_location
-- =======================================
CREATE TABLE "product_location" (
    "product_id" INT NOT NULL REFERENCES "product"(id) ON DELETE CASCADE,
    "location_id" INT NOT NULL REFERENCES "location"(id) ON DELETE CASCADE,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY ("product_id", "location_id")
);

-- =======================================
-- TABLE log
-- =======================================
CREATE TABLE "log" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "level" VARCHAR(20) NOT NULL CHECK (level IN ('info','warning','error','debug')),
    "message" VARCHAR(2500) NOT NULL,
    "source" VARCHAR(20) NOT NULL CHECK (source IN ('API','CRON','FRONT','BACK')) DEFAULT 'BACK',
    "user_id" INT REFERENCES "user"(id) ON DELETE SET NULL,
    "context" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now()
);


COMMIT;
